### ISSUE TITLE
Sites that could be added 

### ISSUE THREAD

**Issue by lordguap** [doprdele/pidpid#43]
http://www.consortium.co.uk/ - Usually receives Yeezy's 
http://www.sneakerboy.com/shop-sneakers/ - Occasional random Yeezy as well as Consortium Shoe
https://www.solebox.com - Gets every release, for major releases (Yeezy) usually doesn't post product page early. 
** **https://www.ymeuniverse.com** ** - Gets consortium, Yeezy's & Nike products, URLS Hidden.

**Comment by doprdele** [comment]
@lordguap I believe consortium and sole links both publish upcoming release pages and therefore would not benefit from scraping. Has this changed for either ?

**Comment by lordguap** [comment]
Consortium usually does just not for Yeezy's, and Solebox does usually as well just occasionally not for hyped consortium drops and yeezy's. I'd say unless you have spare time they can be passed, but i do recommend YME though.

**Comment by doprdele** [comment]
@lordguap I will add Consortium and look into Sneakerboy. I looked into Solebox and it appears that they consistently load early links, so it won't be that useful for me to add it. Unfortunately, we cannot add YME due to conflict of interest - we have team members who are YME employees.

**Comment by doprdele** [comment]
@lordguap You can track the progress of these features in Issue #44 and Issue #45 . I will close this issue shortly.
